Set explicit exit on system tests
Set explicit pass or fail exit status on the system tests.  This
ensures that failing system tests are correctly detected by the
autograder/workflow and given or not given points correctly for the
system tests.

diff --git a/scripts/run-system-tests b/scripts/run-system-tests
--- a/scripts/run-system-tests
+++ b/scripts/run-system-tests
@@ -57,11 +57,15 @@ do
     numtests=$(( numtests + 1 ))
 done
 
+# display final result of tests, give explicit non-zero exit code on failure so workflow detects
+# failed tests
 if [ ${passed} -eq ${numtests} ]
 then
     echo -e "${GREEN}===============================================================================${NORMAL}"
     echo -e "${GREEN}All system tests passed    ${NORMAL} (${passed} tests passed of ${numtests} system tests)"
+    exit 0
 else
     echo -e "${RED}===============================================================================${NORMAL}"
     echo -e "${RED}System test failures detected${NORMAL} (${passed} tests passed of ${numtests} system tests)"
+    exit 1
 fi
